version: '3'

services:
  postgres-compose:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge